### ISSUE TITLE
Charms with a `wheelhouse` fail to install

### ISSUE THREAD

**Issue by n-pochet** [juju-solutions/layer-basic#133]
When installing a reactive charm that uses the `basic` layer with the `bionic` series, it fails to install.
To reproduce:
```
juju deploy --series bionic ubuntu
```
It then gives a failed output in juju:
```
juju status
Model  Controller  Cloud/Region         Version  SLA          Timestamp
test   lxc-ctl     localhost/localhost  2.5.0    unsupported  08:33:10+01:00

App     Version  Status  Scale  Charm   Store       Rev  OS      Notes
ubuntu           error       1  ubuntu  jujucharms   12  ubuntu  

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  error     idle   0        10.0.8.139             hook failed: "install"

Machine  State    DNS         Inst id        Series  AZ  Message
0        started  10.0.8.139  juju-0dda58-0  bionic      Running
```
The logs on `ubuntu/0` show:
```
2019-02-13 07:33:07 ERROR juju.worker.uniter.operation runhook.go:132 hook "install" failed: exit status 1
2019-02-13 07:33:27 DEBUG install Reading package lists...
2019-02-13 07:33:27 DEBUG install Building dependency tree...
2019-02-13 07:33:27 DEBUG install Reading state information...
2019-02-13 07:33:27 DEBUG install E: Unable to locate package python3-pip
2019-02-13 07:33:32 DEBUG install Reading package lists...
2019-02-13 07:33:32 DEBUG install Building dependency tree...
2019-02-13 07:33:32 DEBUG install Reading state information...
2019-02-13 07:33:32 DEBUG install E: Unable to locate package python3-pip
2019-02-13 07:33:38 DEBUG install Reading package lists...
2019-02-13 07:33:38 DEBUG install Building dependency tree...
2019-02-13 07:33:38 DEBUG install Reading state information...
2019-02-13 07:33:38 DEBUG install E: Unable to locate package python3-pip
2019-02-13 07:33:38 DEBUG install Traceback (most recent call last):
2019-02-13 07:33:38 DEBUG install   File "/var/lib/juju/agents/unit-ubuntu-0/charm/hooks/install", line 8, in <module>
2019-02-13 07:33:38 DEBUG install     basic.bootstrap_charm_deps()
2019-02-13 07:33:38 DEBUG install   File "lib/charms/layer/basic.py", line 55, in bootstrap_charm_deps
2019-02-13 07:33:38 DEBUG install     'python3-dev',
2019-02-13 07:33:38 DEBUG install   File "lib/charms/layer/basic.py", line 163, in apt_install
2019-02-13 07:33:38 DEBUG install     check_call(cmd + packages, env=env)
2019-02-13 07:33:38 DEBUG install   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
2019-02-13 07:33:38 DEBUG install     raise CalledProcessError(retcode, cmd)
2019-02-13 07:33:38 DEBUG install subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'python3-pip', 'python3-setuptools', 'python3-yaml', 'python3-dev']' returned non-zero exit status 100.
2019-02-13 07:33:38 ERROR juju.worker.uniter.operation runhook.go:132 hook "install" failed: exit status 1
```
One way to work that issue around is to ssh into the unit and to `sudo apt update`. After resolving the unit, it installs just fine.

**Comment by n-pochet** [comment]
Duplicate of https://github.com/juju-solutions/layer-basic/issues/113
