### ISSUE TITLE
Charm fails with "distutils.errors.DistutilsError: the `allow-hosts` option is not supported when using pip to install requirements."

### ISSUE THREAD

**Issue by gnuoy** [juju-solutions/layer-basic#149]
If a charm has a wheelhouse then a pydistutils.cfg file is written *1 This contains the allow_hosts option which appears to be no longer supported when using pip:

```
2019-12-04 13:37:29 DEBUG install Processing ./wheelhouse/debtcollector-1.22.0.tar.gz
2019-12-04 13:37:29 DEBUG install     Complete output from command python setup.py egg_info:
2019-12-04 13:37:29 DEBUG install     Traceback (most recent call last):
2019-12-04 13:37:29 DEBUG install       File "<string>", line 1, in <module>
2019-12-04 13:37:29 DEBUG install       File "/tmp/pip-req-build-oddsnayu/setup.py", line 29, in <module>
2019-12-04 13:37:29 DEBUG install         pbr=True)
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
2019-12-04 13:37:29 DEBUG install         _install_setup_requires(attrs)
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
2019-12-04 13:37:29 DEBUG install         dist.fetch_build_eggs(dist.setup_requires)
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
2019-12-04 13:37:29 DEBUG install         replace_conflicting=True,
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 782, in resolve
2019-12-04 13:37:29 DEBUG install         replace_conflicting=replace_conflicting
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1065, in best_match
2019-12-04 13:37:29 DEBUG install         return self.obtain(req, installer)
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1077, in obtain
2019-12-04 13:37:29 DEBUG install         return installer(requirement)
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
2019-12-04 13:37:29 DEBUG install         return fetch_build_egg(self, req)
2019-12-04 13:37:29 DEBUG install       File "/var/lib/juju/agents/unit-tempest2-0/.venv/lib/python3.5/site-packages/setuptools/installer.py", line 83, in fetch_build_egg
2019-12-04 13:37:29 DEBUG install         raise DistutilsError('the `allow-hosts` option is not supported '
2019-12-04 13:37:29 DEBUG install     distutils.errors.DistutilsError: the `allow-hosts` option is not supported when using pip to install requirements.
```

*1 https://github.com/juju-solutions/layer-basic/blob/master/lib/charms/layer/basic.py#L66

**Comment by gnuoy** [comment]
I am missing piece of the puzzle because I am only seeing this on one charm atm and there are a number which have wheelhouses

**Comment by gnuoy** [comment]
I think *1 shows this issue is not going away

*1 https://github.com/pypa/setuptools/issues/1916

**Comment by raulikeda** [comment]
Just for the ones who's seeking some workaround:

Solved temporarily by editing this file in the application machine. After installing the charm and getting the error "Hook Failed: install"

1. Connect the machine
$ juju ssh unit-name/#
2. Edit the file:
/var/lib/juju/agents/unit-name/cham/lib/charms/layer/basic.py
3. Comment the line that contains: "allow-hosts"
4. Go back to controller client
4. If it doesn't solve the error automaticaly:
$ juju resolve unit-name

probably not a definitive solution neither works for any charm.

**Comment by ajkavanagh** [comment]
I've had the same on octavia-dashboard on focal:

```2020-04-22 10:22:22 DEBUG install     ERROR: Command errored out with exit status 1:
2020-04-22 10:22:22 DEBUG install      command: /var/lib/juju/agents/unit-octavia-0/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-un47gj1v/sqlalchemy-migrate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-un47gj1v/sqlalchemy-migrate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-un47gj1v/sqlalchemy-migrate/pip-egg-info
2020-04-22 10:22:22 DEBUG install          cwd: /tmp/pip-install-un47gj1v/sqlalchemy-migrate/
2020-04-22 10:22:22 DEBUG install     Complete output (21 lines):
2020-04-22 10:22:22 DEBUG install     Traceback (most recent call last):
2020-04-22 10:22:22 DEBUG install       File "<string>", line 1, in <module>
2020-04-22 10:22:22 DEBUG install       File "/tmp/pip-install-un47gj1v/sqlalchemy-migrate/setup.py", line 27, in <module>
2020-04-22 10:22:22 DEBUG install         setuptools.setup(
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
2020-04-22 10:22:22 DEBUG install         _install_setup_requires(attrs)
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
2020-04-22 10:22:22 DEBUG install         dist.fetch_build_eggs(dist.setup_requires)
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
2020-04-22 10:22:22 DEBUG install         resolved_dists = pkg_resources.working_set.resolve(
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
2020-04-22 10:22:22 DEBUG install         dist = best[req.key] = env.best_match(
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
2020-04-22 10:22:22 DEBUG install         return self.obtain(req, installer)
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
2020-04-22 10:22:22 DEBUG install         return installer(requirement)
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
2020-04-22 10:22:22 DEBUG install         return fetch_build_egg(self, req)
2020-04-22 10:22:22 DEBUG install       File "/var/lib/juju/agents/unit-octavia-0/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 83, in fetch_build_egg
2020-04-22 10:22:22 DEBUG install         raise DistutilsError('the `allow-hosts` option is not supported '
2020-04-22 10:22:22 DEBUG install     distutils.errors.DistutilsError: the `allow-hosts` option is not supported when using pip to install requirements.
```
