### ISSUE TITLE
Trusty deploy fails because Jinja2 and PyYaml have dropped support for python 3.4

### ISSUE THREAD

**Issue by coreycb** [juju-solutions/layer-basic#152]
2020-01-30 20:31:23 DEBUG install Processing ./wheelhouse/PyYAML-5.3.tar.gz
2020-01-30 20:31:24 DEBUG install PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.3
2020-01-30 20:31:24 DEBUG install Traceback (most recent call last):
2020-01-30 20:31:24 DEBUG install   File "/var/lib/juju/agents/unit-aodh-0/charm/hooks/install", line 8, in <module>
2020-01-30 20:31:24 DEBUG install     basic.bootstrap_charm_deps()
2020-01-30 20:31:24 DEBUG install   File "lib/charms/layer/basic.py", line 117, in bootstrap_charm_deps
2020-01-30 20:31:24 DEBUG install     '-f', 'wheelhouse'] + glob('wheelhouse/*'))
2020-01-30 20:31:24 DEBUG install   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
2020-01-30 20:31:24 DEBUG install     raise CalledProcessError(retcode, cmd)
2020-01-30 20:31:24 DEBUG install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-aodh-0/.venv/bin/pip', 'install', '-U', '--ignore-installed', '--no-index', '-f', 'wheelhouse', 'wheelhouse/wheel-0.33.6.tar.gz', 'wheelhouse/charms.openstack-0.0.1.dev1.zip', 'wheelhouse/netaddr-0.7.19.tar.gz', 'wheelhouse/psutil-5.6.7.tar.gz', 'wheelhouse/six-1.14.0.tar.gz', 'wheelhouse/setuptools_scm-1.17.0.tar.gz', 'wheelhouse/pip-18.1.tar.gz', 'wheelhouse/dnspython-1.16.0.zip', 'wheelhouse/charmhelpers-0.20.8.tar.gz', 'wheelhouse/setuptools-41.6.0.zip', 'wheelhouse/PyYAML-5.3.tar.gz', 'wheelhouse/netifaces-0.10.9.tar.gz', 'wheelhouse/charms.reactive-1.3.0.tar.gz', 'wheelhouse/pyaml-19.12.0.tar.gz', 'wheelhouse/Jinja2-2.11.1.tar.gz', 'wheelhouse/MarkupSafe-1.1.1.tar.gz', 'wheelhouse/Tempita-0.5.2.tar.gz']' returned non-zero exit status 1
2020-01-30 20:31:24 ERROR juju.worker.uniter.operation runhook.go:132 hook "install" failed: exit status 1

**Comment by coreycb** [comment]
Note: trusty is getting supported up to 2024 for ESM

**Comment by coreycb** [comment]
Upstream commits that removed 3.4 support:
https://github.com/yaml/pyyaml/commit/039c9eb3082de06063fa669cf41a73dbeabb5d84
https://github.com/pallets/jinja/commit/38165dfeba9d73de52ce90442e7ec8f491dceda7

**Comment by coreycb** [comment]
For pyyaml, 5.2 supports 3.4; 5.3 doesn't support it.
For jinja, 2.10.1 supports 3.4; 2.10.2 doesn't support it.
