### ISSUE TITLE
regression: Offline deployments break on eoan and onwards

### ISSUE THREAD

**Issue by fnordahl** [juju-solutions/layer-basic#171]
The change made in #169 introduced a regression that breaks offline deployments for Eoan and onwards.

https://github.com/juju-solutions/layer-basic/blob/97b0efe8f8609db59c1634e84ed133814bc8156d/lib/charms/layer/basic.py#L127-L138

With ^ you get:
```
2020-05-15 13:12:31 DEBUG install Processing ./wheelhouse/sriov-netplan-shim-0.1.1.tar.gz
2020-05-15 13:13:03 DEBUG install     ERROR: Command errored out with exit status 1:
2020-05-15 13:13:03 DEBUG install      command: /var/lib/juju/agents/unit-ovn-central-3/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fb5_72lm/sriov-netplan-shim/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fb5_72lm/sriov-netplan-shim/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fb5_72lm/sriov-netplan-shim/pip-egg-info
2020-05-15 13:13:03 DEBUG install          cwd: /tmp/pip-install-fb5_72lm/sriov-netplan-shim/
2020-05-15 13:13:03 DEBUG install     Complete output (37 lines):
2020-05-15 13:13:03 DEBUG install     WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb226d7d30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/pbr/
2020-05-15 13:13:03 DEBUG install     WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb226d79d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/pbr/
2020-05-15 13:13:03 DEBUG install     WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb226d7400>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/pbr/
2020-05-15 13:13:03 DEBUG install     WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb226d7790>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/pbr/
2020-05-15 13:13:03 DEBUG install     WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb226d7670>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/pbr/
2020-05-15 13:13:03 DEBUG install     ERROR: Could not find a version that satisfies the requirement pbr (from versions: none)
2020-05-15 13:13:03 DEBUG install     ERROR: No matching distribution found for pbr
2020-05-15 13:13:03 DEBUG install     Traceback (most recent call last):
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
2020-05-15 13:13:03 DEBUG install         subprocess.check_call(cmd)
2020-05-15 13:13:03 DEBUG install       File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
2020-05-15 13:13:03 DEBUG install         raise CalledProcessError(retcode, cmd)
2020-05-15 13:13:03 DEBUG install     subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-ovn-central-3/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1txf5359', '--quiet', 'pbr']' returned non-zero exit status 1.
2020-05-15 13:13:03 DEBUG install     
2020-05-15 13:13:03 DEBUG install     During handling of the above exception, another exception occurred:
2020-05-15 13:13:03 DEBUG install     
2020-05-15 13:13:03 DEBUG install     Traceback (most recent call last):
2020-05-15 13:13:03 DEBUG install       File "<string>", line 1, in <module>
2020-05-15 13:13:03 DEBUG install       File "/tmp/pip-install-fb5_72lm/sriov-netplan-shim/setup.py", line 27, in <module>
2020-05-15 13:13:03 DEBUG install         setuptools.setup(
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
2020-05-15 13:13:03 DEBUG install         _install_setup_requires(attrs)
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
2020-05-15 13:13:03 DEBUG install         dist.fetch_build_eggs(dist.setup_requires)
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
2020-05-15 13:13:03 DEBUG install         resolved_dists = pkg_resources.working_set.resolve(
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
2020-05-15 13:13:03 DEBUG install         dist = best[req.key] = env.best_match(
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
2020-05-15 13:13:03 DEBUG install         return self.obtain(req, installer)
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
2020-05-15 13:13:03 DEBUG install         return installer(requirement)
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
2020-05-15 13:13:03 DEBUG install         return fetch_build_egg(self, req)
2020-05-15 13:13:03 DEBUG install       File "/var/lib/juju/agents/unit-ovn-central-3/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
2020-05-15 13:13:03 DEBUG install         raise DistutilsError(str(e))
2020-05-15 13:13:03 DEBUG install     distutils.errors.DistutilsError: Command '['/var/lib/juju/agents/unit-ovn-central-3/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1txf5359', '--quiet', 'pbr']' returned non-zero exit status 1.
2020-05-15 13:13:03 DEBUG install     ----------------------------------------
2020-05-15 13:13:03 DEBUG install ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-05-15 13:13:03 DEBUG install Traceback (most recent call last):
2020-05-15 13:13:03 DEBUG install   File "/var/lib/juju/agents/unit-ovn-central-3/charm/hooks/install", line 8, in <module>
2020-05-15 13:13:03 DEBUG install     basic.bootstrap_charm_deps()
2020-05-15 13:13:03 DEBUG install   File "lib/charms/layer/basic.py", line 185, in bootstrap_charm_deps
2020-05-15 13:13:03 DEBUG install     check_call([pip, 'install', '-U', reinstall_flag, '--no-index',
2020-05-15 13:13:03 DEBUG install   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
2020-05-15 13:13:03 DEBUG install     raise CalledProcessError(retcode, cmd)
2020-05-15 13:13:03 DEBUG install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-ovn-central-3/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'MarkupSafe', 'dnspython', 'Tempita', 'PyYAML', 'sriov-netplan-shim', 'netifaces', 'charms.openstack', 'pbr', 'psutil', 'wheel', 'charmhelpers', 'charms.reactive', 'pyaml', 'Jinja2', 'six', 'netaddr']' returned non-zero exit status 1.
```

I have confirmed that if we add back the `/root/.pydistutils.cfg` with the `find_links` attribute the installation succeeds.

**Comment by fnordahl** [comment]
For reference: https://bugs.launchpad.net/charm-layer-ovn/+bug/1878626
