### ISSUE TITLE
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index'

### ISSUE THREAD

**Issue by hloeung** [juju-solutions/layer-basic#183]
Hi,

On a few subordinates, namely ntp, livepatch, and telegraf, hooks are failing with the following:

`2020-07-10 04:11:11 DEBUG upgrade-charm Traceback (most recent call last):`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/bin/pip", line 5, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal import main`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal.cli.autocompletion import autocomplete`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal.cli.main_parser import create_main_parser`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal.commands import (`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal.commands.completion import CompletionCommand`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal.cli.base_command import Command`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 23, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     from pip._internal.index import PackageFinder`
`2020-07-10 04:11:11 DEBUG upgrade-charm ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/var/lib/juju/agents/unit-livepatch-0/.venv/lib/python3.8/site-packages/pip/_internal/index/__init__.py)`
`2020-07-10 04:11:11 DEBUG upgrade-charm Traceback (most recent call last):`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-livepatch-0/charm/hooks/upgrade-charm", line 8, in <module>`
`2020-07-10 04:11:11 DEBUG upgrade-charm     basic.bootstrap_charm_deps()`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "lib/charms/layer/basic.py", line 108, in bootstrap_charm_deps`
`2020-07-10 04:11:11 DEBUG upgrade-charm     check_call([pip, 'install', '-U', '--no-index', '-f', 'wheelhouse',`
`2020-07-10 04:11:11 DEBUG upgrade-charm   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call`
`2020-07-10 04:11:11 DEBUG upgrade-charm     raise CalledProcessError(retcode, cmd)`
`2020-07-10 04:11:11 DEBUG upgrade-charm subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-livepatch-0/.venv/bin/pip', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'pip']' returned non-zero exit status 1.`
`2020-07-10 04:11:11 ERROR juju.worker.uniter.operation runhook.go:136 hook "upgrade-charm" (via explicit, bespoke hook script) failed: exit status 1`

I'm not sure if it's related to https://github.com/juju-solutions/layer-basic/issues/95

These subordinates have pip pinned with pip-18.1 bundled via wheelhouse:

`ubuntu@machine-0:/var/lib/juju/agents$ grep pip */charm/.build.manifest`
`unit-livepatch-0/charm/.build.manifest:    "wheelhouse/pip-18.1.tar.gz": [`
`unit-ntp-0/charm/.build.manifest:    "wheelhouse/pip-18.1.tar.gz": [`
`unit-telegraf-0/charm/.build.manifest:    "wheelhouse/pip-18.1.tar.gz": [`

The system was deployed using Focal so has pip 20.0.2 installed.

**Comment by hloeung** [comment]
Looks to be fixed in https://github.com/juju-solutions/layer-basic/pull/160

So guess just have to go through and rebuild these charms
