### ISSUE TITLE
Install hook fails due to python-yaml already existing in system

### ISSUE THREAD

**Issue by 1stvamp** [juju-solutions/layer-basic#27]
Did a rebuild of my layer this morning and now my charm can't be installed as it errors in the base-layer install hook trying to install the pyyaml wheel:

```
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40 Installing collected packages: MarkupSafe, PyYAML, pip, netaddr, pyaml, Tempita, six, Jinja2, charmhelpers, charms.reactive
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40   Found existing installation: PyYAML 3.10
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40 Detected a distutils installed project ('PyYAML') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40 Traceback (most recent call last):
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40   File "/var/lib/juju/agents/unit-errbot-1/charm/hooks/install", line 8, in <module>
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40     bootstrap_charm_deps()
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40   File "lib/charms/bootstrap.py", line 18, in bootstrap_charm_deps
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40     check_call(['pip3', 'install', '-U', '--no-index', '-f', 'wheelhouse'] + glob('wheelhouse/*'))
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40   File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40     if retcode:
unit-errbot-1[2474]: 2016-01-21 11:05:48 INFO unit.errbot/1.install logger.go:40 subprocess.CalledProcessError: Command '['pip3', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'wheelhouse/MarkupSafe-0.23.tar.gz', 'wheelhouse/PyYAML-3.11.tar.gz', 'wheelhouse/pip-8.0.0.tar.gz', 'wheelhouse/netaddr-0.7.18.tar.gz', 'wheelhouse/pyaml-15.8.2.tar.gz', 'wheelhouse/Tempita-0.5.2.tar.gz', 'wheelhouse/charms.reactive-0.3.8.tar.gz', 'wheelhouse/charmhelpers-0.6.1.tar.gz', 'wheelhouse/six-1.10.0.tar.gz', 'wheelhouse/Jinja2-2.8.tar.gz']' returned non-zero exit status 1
unit-errbot-1[2474]: 2016-01-21 11:05:48 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```

**Comment by johnsca** [comment]
Once charm-tools 1.11.1 is released, this should be fixed by #28

**Comment by johnsca** [comment]
Seems fixed to me, but I didn't see this error for PyYAML, just pip.  Can you re-test and close this issue if resolved?

**Comment by johnsca** [comment]
Closing assuming this is resolved.  Reopen if still an issue.
