### ISSUE TITLE
Null values in config.yaml raises KeyError exception

### ISSUE THREAD

**Issue by gnuoy** [juju-solutions/layer-basic#64]
A null value in the config.yaml cause charm install to fail with:

2016-04-29 21:34:29 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
2016-04-29 21:35:52 INFO install Traceback (most recent call last):
2016-04-29 21:35:52 INFO install   File "/var/lib/juju/agents/unit-congress-3/charm/hooks/install", line 9, in <module>
2016-04-29 21:35:52 INFO install     basic.init_config_states()
2016-04-29 21:35:52 INFO install   File "lib/charms/layer/basic.py", line 139, in init_config_states
2016-04-29 21:35:52 INFO install     toggle_state('config.set.{}'.format(opt), config[opt])
2016-04-29 21:35:52 INFO install KeyError: 'os-public-hostname'

**Comment by cmars** [comment]
I think I'm seeing something similar. I have a charm that has no default: value for a config key and the latest basic-layer (could be #63) is erroring out in the install hook now with a KeyError:
```
2016-04-29 22:36:16 INFO juju.worker.uniter resolver.go:107 awaiting error resolution for "install" hook
2016-04-29 22:36:16 INFO worker.uniter.jujuc server.go:173 running hook tool "config-get" ["--format=json"]
2016-04-29 22:36:16 INFO install Traceback (most recent call last):
2016-04-29 22:36:16 INFO install   File "/var/lib/juju/agents/unit-gogs-oss-0/charm/hooks/install", line 9, in <module>
2016-04-29 22:36:16 INFO install     basic.init_config_states()
2016-04-29 22:36:16 INFO install   File "lib/charms/layer/basic.py", line 139, in init_config_states
2016-04-29 22:36:16 INFO install     toggle_state('config.set.{}'.format(opt), config[opt])
2016-04-29 22:36:16 INFO install KeyError: 'host'
```
