### ISSUE TITLE
use_venv breaks on trusty

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-basic#81]
use_venv breaks on trusty because platform doesn't seem to return the series, see below

2016-12-22 01:53:49 INFO install E: Unable to locate package virtualenv
2016-12-22 01:53:49 INFO install Traceback (most recent call last):
2016-12-22 01:53:49 INFO install   File "/var/lib/juju/agents/unit-newrelic-sysmond-trusty-8/charm/hooks/install", line 8, in <module>
2016-12-22 01:53:49 INFO install     basic.bootstrap_charm_deps()
2016-12-22 01:53:49 INFO install   File "lib/charms/layer/basic.py", line 53, in bootstrap_charm_deps
2016-12-22 01:53:49 INFO install     apt_install(['virtualenv'])
2016-12-22 01:53:49 INFO install   File "lib/charms/layer/basic.py", line 146, in apt_install
2016-12-22 01:53:49 INFO install     check_call(cmd + packages, env=env)
2016-12-22 01:53:49 INFO install   File "/usr/local/lib/python3.5/subprocess.py", line 584, in check_call
2016-12-22 01:53:49 INFO install     raise CalledProcessError(retcode, cmd)
2016-12-22 01:53:49 INFO install subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'virtualenv']' returned non-zero exit status 100
2016-12-22 01:53:49 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

**Comment by jamesbeedy** [comment]
a little investigation shows -> 


ubuntu@831889-PRMSrch1:~$ python3
Python 3.5.0 (default, Nov 26 2016, 13:30:38) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> distname, version, series = platform.linux_distribution()
>>> series
''
>>>

**Comment by jamesbeedy** [comment]
Uhhhh. Now, following the change to lsb_release from charmhelpers, I'm getting -> http://paste.ubuntu.com/23666794/
