### ISSUE TITLE
Attempt to preserve system pip doesn't work

### ISSUE THREAD

**Issue by bloodearnest** [juju-solutions/layer-basic#95]
Currently, when not using a virtualenv, bootstrap_charm_deps() function saves a copy of /usr/bin/pip3, pip upgrades the system pip, and then restores the copy of /usr/bin/pip

This is presumably trying to undo the effect of pip-upgrading pip. But it does not achieve this, as the /usr/bin/pip3 file is just an entrypoint, that uses "from pip import main", and the pip upgrade is still in
/usr/local/lib/python3.5/dist-packages, and is used by the restored /usr/bin/pip3 just fine

Please consider just pip3 uninstalling pip, which DTRT. Or maybe use pip install --user?

**Comment by johnsca** [comment]
The intent of that code is not to preserve the version of pip for Python 3 to the lower version, but rather to prevent `pip3 install -U pip` from changing the Python version used by the default pip command from Python 2 to Python 3.  However, it seems from a quick test (on a fresh trusty cloud image) that it may be unnecessary:

```
ubuntu@juju-7f1395-1:~$ sudo pip3 install -U pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python3/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
ubuntu@juju-7f1395-1:~$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
ubuntu@juju-7f1395-1:~$ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)
```

I don't recall if that was from an actual issue encountered at the time or if it was just defensive paranoia.  I don't think it's hurting anything, but I'm not against removing it.

**Comment by hloeung** [comment]
Would this bug be the cause of:

2020-07-10 04:14:28 DEBUG upgrade-charm Traceback (most recent call last):
2020-07-10 04:14:28 DEBUG upgrade-charm   File "/var/lib/juju/agents/unit-ntp-0/charm/hooks/upgrade-charm", line 8, in <module>
2020-07-10 04:14:28 DEBUG upgrade-charm     basic.bootstrap_charm_deps()
2020-07-10 04:14:28 DEBUG upgrade-charm   File "lib/charms/layer/basic.py", line 170, in bootstrap_charm_deps
2020-07-10 04:14:28 DEBUG upgrade-charm     check_call([pip, 'install', '-U', '--no-index', '-f', 'wheelhouse',
2020-07-10 04:14:28 DEBUG upgrade-charm   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
2020-07-10 04:14:28 DEBUG upgrade-charm     raise CalledProcessError(retcode, cmd)
2020-07-10 04:14:28 DEBUG upgrade-charm subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-ntp-0/.venv/bin/pip', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'pip']' returned non-zero exit status 1.
2020-07-10 04:14:28 ERROR juju.worker.uniter.operation runhook.go:136 hook "upgrade-charm" (via explicit, bespoke hook script) failed: exit status 1

Seeing it with a couple of subordinate charms

**Comment by hloeung** [comment]
These subordinates seems to be the only ones with pip bundled, and an older version to the system on

ubuntu@machine-0:/var/lib/juju/agents/unit-livepatch-0/charm$ dpkg -l | grep pip
ii  libpipeline1:amd64                   1.5.2-2build1                                 amd64        Unix process pipeline manipulation library
ii  python-pip-whl                       20.0.2-5ubuntu1                               all          Python package installer
ii  python3-pip                          20.0.2-5ubuntu1                               all          Python package installer
ubuntu@machine-0:/var/lib/juju/agents/unit-livepatch-0/charm$ cd ../../
ubuntu@machine-0:/var/lib/juju/agents$ grep pip */charm/.build.manifest
unit-livepatch-0/charm/.build.manifest:    "wheelhouse/pip-18.1.tar.gz": [
unit-ntp-0/charm/.build.manifest:    "wheelhouse/pip-18.1.tar.gz": [
unit-telegraf-0/charm/.build.manifest:    "wheelhouse/pip-18.1.tar.gz": [
